export const CLUB_OPTIONS = [
  "General",
  "Slug & Plug",
  "Sketch",
  "Tech-Wiz",
  "Andropedia",
  "Codekrafters",
  "Chipset",
  "Logicplay",
  "Intellects",
  "Synergies",
  "Techpro",
  "Gamecon",
  "Techvayuna",
  "Cyborg",
  "Developers Student Club",
  "Codezilla",
  "Journal Club",
  "Eleet Club",
  "Foreign Language Club",
];
